name = "toptenuae"
compatibility_date = "2024-01-01"

pages_build_output_dir = ".open-next/worker"

[site]
bucket = ".open-next/worker"

# Add compatibility flags for Next.js features
compatibility_flags = ["nodejs_compat"]
